name: metrics_env0
channels:
  - anaconda
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - matplotlib=3.5.3
  - nibabel=4.0.2
  - pandas=1.3.5
  - python=3.7.13
  - pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  - pytorch-cuda=11.7
  - pip=22.3.1
  - requests==2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tensorflow=2.4.1
  - theano=1.0.2
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tqdm=4.64.1
  # - pip:
  #     - click==8.1.7
  #     - ninja==1.11.1.1
#      - requests==2.31.0 # 2.28.1 to avoid "Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!"
